[book]
authors = ["Khan Kibria"]
language = "en"
multilingual = false
src = "src"
title = "My Development Cookbook"

[build]
build-dir = "gh-pages/docs"

# mdbook-frntmtr can be installed from github with,
# cargo install --git https://github.com/kkibria/mdbook-frntmtr.git
[preprocessor.frntmtr]
# command = "mdbook-frntmtr"

[preprocessor.svgdx]
# local copy 
# command = "cargo run --manifest-path D:/mdbook-svgdx/Cargo.toml --quiet"
